### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by viruz82** [Technosoft2000/docker-sickrage-cytec#1]
Hi,

ich habe folgendes im Log stehen
```WARNING::MAIN :: DB error: database is locked```

Es gibt sonst keinen weiteren Prozess, der auf die Datenbank zugreift. Ich kann mir das nicht erklären.

Hat jemand dasselbe Problem oder besser eine Lösung dafür? Das Problem ist, dass dadurch das Webinterface unerträglich langsam ist.

**Comment by Technosoft2000** [comment]
Hi @viruz82,

ich kann hier bei meinen laufenden Container dieses Problem nicht nachvollziehen, konnte somit in den Logs solch einen Eintrag nicht finden. 

Hab jedoch ein bisschen gegoogled und in Sickrage Foren wird oftmals beschrieben dass dann die Datenbank defekt ist wenn solch ein Problem auftritt. Am besten du sicherst dir mal die Datenbank Dateien weg und startest Sickrage ohne diese so dass neue erstellt werden und legst deine Serien neu an, was natürlich sicher ein Haufen Aufwand sein wird wenn man eine Menge Serien hat. Sollte dann noch immer das Problem auftreten dann liegt es an was anderen.

**Comment by viruz82** [comment]
Hi @Technosoft2000 ,

ja, du hattest Recht. Es lag, warum auch immer, tatsächlich an der DB.
Neu gemacht --> funzt. :+1:
