### ISSUE TITLE
Sickrage als root

### ISSUE THREAD

**Issue by viruz82** [Technosoft2000/docker-sickrage-cytec#2]
Hi @Technosoft2000 ,

aufgrund von Berechtigungen auf Freigaben muss ich Sickrage als root laufen lassen.
Das scheint allerdings nicht zu funktionieren.

Wenn ich PUID=0 und PGID=0 als Parameter mitgebe, kommt es zu folgendem Fehler und der Container startet nicht.

```
/init/config.sh: line 25: [: too many arguments
adduser: uid '0' in use
chown: invalid user: ‘sickrage:sickrage’
error: failed switching to "sickrage:sickrage": unable to find user sickrage: no matching entries in passwd file
error: failed switching to "sickrage:sickrage": unable to find user sickrage: no matching entries in passwd file
error: failed switching to "sickrage:sickrage": unable to find user sickrage: no matching entries in passwd file
error: failed switching to "sickrage:sickrage": unable to find user sickrage: no matching entries in passwd file
error: failed switching to "sickrage:sickrage": unable to find user sickrage: no matching entries in passwd file
```

Hast du eine Idee, wie ich Sickrage als root ans Laufen bekomme?

**Comment by Technosoft2000** [comment]
Hi @viruz82,

dazu muss ich das image auf das aktuelle Basis-Image umstellen, in diesem habe ich das Feature schon integriert. Hoffe ich komme dieses Wochenende dazu, gebe dir Bescheid.

**Comment by viruz82** [comment]
Moin @Technosoft2000 ,

sauber, ich danke dir vielmals. :+1:

**Comment by Technosoft2000** [comment]
Hi @viruz82 ,

neue Release v1.1.4 ist nun verfügbar, bitte testen, danke :)

**Comment by viruz82** [comment]
Hi @Technosoft2000 ,

funzt 1A. Vielen Dank! :+1:
