### ISSUE TITLE
Keine Suchergebnisse

### ISSUE THREAD

**Issue by viruz82** [Technosoft2000/docker-sickrage-cytec#3]
Moin @Technosoft2000 ,

ich bekomme seit einiger Zeit keine Suchergebnisse mehr, wenn ich eine Serie hinzufügen will.
Allerdings habe ich gerade keinen Lösungsansatz. Ist dir da was bekannt?

**Comment by Technosoft2000** [comment]
Servus @viruz82,

dieses Problem habe ich auch vor ca. einer Woche entdeckt und die Lösung ist es auf https://github.com/Technosoft2000/sickchill umzusteigen. Achtung die Volume Mappings sind hier etwas anders. Die sickbeard.ini config musste ich dann in das data Verzeichnis verschieben und umbenennen auf config.ini . Nach dem Container Start muss man dann in Sickchill einstellen wo er die Serien und Downloads dann findet. Am besten vorher ein Backup erstellen vom Sickbeard config und data Verzeichnis.

**Comment by viruz82** [comment]
Alles klar. Vielen Dank @Technosoft2000
